### ISSUE TITLE
2DA files are empty

### ISSUE THREAD

**Issue by suy** [btigi/iiKeyNames#1]
I've not been able to try the mod yet, but when looking at which items the mod affects, I've found the 2DA files to be empty. I assume that's an issue to fix. :)

**Comment by btigi** [comment]
The 2da files are intended to be empty. During installation, all ARE files are dynamically scanned for any "key" items required to activate doors - such items are they appended to the 2da files, which are then used as the basis for further processing.
The mod would likely be written differently with the options available in WeiDU in 2021 :)

**Comment by suy** [comment]
I'm ignorant enough of WeiDU in 2021 that I thought that the 2da files were read to know which key items were modified. 😅 
Looking forward to use this, thank you.
